---
- yum: 
    name:
      - epel-release
      - zip
      - unzip
      - bzip2
      - wget
      - libselinux-python
      - policycoreutils-python
      - git
      - curl
      - mc
    state: present